-- FINAL_SUPABASE_MIGRATION.sql
-- Purpose: final, consolidated database blueprint for a verified Supabase environment.
-- This file is intentionally not executed in the current workspace.
-- It must be run only after the target database has been inspected and verified.

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Required extensions
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- 2. Safe validation for existing core tables
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'profiles'
  ) THEN
    RAISE EXCEPTION 'Required table public.profiles is missing. Verify live schema before execution.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'products'
  ) THEN
    RAISE EXCEPTION 'Required table public.products is missing. Verify live schema before execution.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'orders'
  ) THEN
    RAISE EXCEPTION 'Required table public.orders is missing. Verify live schema before execution.';
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 3. Existing working order contract upgrades
-- -----------------------------------------------------------------------------
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_customer_idempotency_key
  ON public.orders (customer_id, idempotency_key)
  WHERE customer_id IS NOT NULL AND idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_customer_id_created_at
  ON public.orders (customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_status
  ON public.orders (status);

-- -----------------------------------------------------------------------------
-- 4. Profiles contract (safe if table already exists)
-- -----------------------------------------------------------------------------
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS mobile TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS phone_number TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS pincode TEXT,
  ADD COLUMN IF NOT EXISTS landmark TEXT,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_profiles_mobile
  ON public.profiles (mobile);

CREATE INDEX IF NOT EXISTS idx_profiles_phone_number
  ON public.profiles (phone_number);

-- -----------------------------------------------------------------------------
-- 5. Customer addresses (planned final shape)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customer_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  label TEXT NOT NULL DEFAULT 'Home',
  full_name TEXT,
  phone TEXT,
  address TEXT NOT NULL,
  landmark TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT NOT NULL,
  address_type TEXT NOT NULL DEFAULT 'Home',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT customer_addresses_address_type_check
    CHECK (address_type IN ('Home', 'Work', 'Other'))
);

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user_created_at
  ON public.customer_addresses (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user_default
  ON public.customer_addresses (user_id, is_default DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_addresses_single_default
  ON public.customer_addresses (user_id)
  WHERE is_default = TRUE;

-- -----------------------------------------------------------------------------
-- 6. Wallet tables (secure ledger model)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wallets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  balance NUMERIC NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'INR',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL REFERENCES public.wallets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('credit', 'debit', 'refund', 'cashback', 'admin_adjustment')),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  currency TEXT NOT NULL DEFAULT 'INR',
  reference_type TEXT,
  reference_id TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_created_at
  ON public.wallet_transactions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_wallet_created_at
  ON public.wallet_transactions (wallet_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- 7. Coupon / rewards tables
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.coupons (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  title TEXT,
  discount_type TEXT NOT NULL DEFAULT 'percent',
  discount_value NUMERIC NOT NULL DEFAULT 0,
  min_order_value NUMERIC DEFAULT 0,
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.customer_coupon_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  coupon_id TEXT NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE,
  used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  order_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customer_coupon_usage_user
  ON public.customer_coupon_usage (user_id, used_at DESC);

-- -----------------------------------------------------------------------------
-- 8. Notification and support tables
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  order_updates BOOLEAN NOT NULL DEFAULT TRUE,
  promotional_updates BOOLEAN NOT NULL DEFAULT TRUE,
  offers BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 9. Store configuration table
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.store_config (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 10. Existing checkout RPC: keep canonical architecture
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.place_website_order_atomic(
  p_customer_id text,
  p_customer_name text,
  p_customer_phone text,
  p_shipping_address text,
  p_landmark text DEFAULT NULL,
  p_pincode text DEFAULT NULL,
  p_payment_method text DEFAULT 'cod',
  p_idempotency_key text DEFAULT NULL,
  p_items jsonb DEFAULT '[]'::jsonb
)
RETURNS TABLE (
  id text,
  total numeric,
  subtotal numeric,
  status text,
  payment_status text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_auth_user uuid;
  v_customer_uuid uuid;
  v_order_id text;
  v_item jsonb;
  v_product_id bigint;
  v_quantity integer;
  v_product record;
  v_unit_price numeric;
  v_line_total numeric;
  v_subtotal numeric := 0;
BEGIN
  v_auth_user := auth.uid();
  IF v_auth_user IS NULL THEN
    RAISE EXCEPTION 'Authentication required for website checkout';
  END IF;

  IF p_customer_id IS NULL OR btrim(p_customer_id) = '' THEN
    RAISE EXCEPTION 'customer_id is required';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' THEN
    RAISE EXCEPTION 'items must be a JSON array';
  END IF;

  IF jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Cart is empty';
  END IF;

  v_customer_uuid := p_customer_id::uuid;
  IF v_auth_user <> v_customer_uuid THEN
    RAISE EXCEPTION 'Customer identity mismatch';
  END IF;

  IF p_idempotency_key IS NOT NULL THEN
    SELECT o.id INTO v_order_id
    FROM public.orders o
    WHERE o.customer_id = p_customer_id
      AND o.idempotency_key = p_idempotency_key
    LIMIT 1;

    IF v_order_id IS NOT NULL THEN
      RETURN QUERY
      SELECT o.id::text,
             COALESCE(o.total, 0),
             COALESCE(o.subtotal, 0),
             COALESCE(o.status, 'pending'),
             COALESCE(o.payment_status, 'pending')
      FROM public.orders o
      WHERE o.id = v_order_id;
      RETURN;
    END IF;
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id := NULLIF((v_item ->> 'product_id')::text, '')::bigint;
    v_quantity := NULLIF((v_item ->> 'quantity')::text, '')::integer;

    IF v_product_id IS NULL OR v_quantity IS NULL OR v_quantity <= 0 THEN
      RAISE EXCEPTION 'Invalid item payload';
    END IF;

    SELECT p.* INTO v_product
    FROM public.products p
    WHERE p.id = v_product_id
    FOR UPDATE;

    IF v_product.id IS NULL THEN
      RAISE EXCEPTION 'Product not found: %', v_product_id;
    END IF;

    IF v_product.is_deleted = TRUE THEN
      RAISE EXCEPTION 'Product is unavailable: %', v_product_id;
    END IF;

    IF v_product.is_active = FALSE THEN
      RAISE EXCEPTION 'Product is inactive: %', v_product_id;
    END IF;

    IF COALESCE(v_product.stock, 0)::numeric < v_quantity THEN
      RAISE EXCEPTION 'Insufficient stock for product %', v_product_id;
    END IF;

    v_unit_price := COALESCE(
      v_product.sale_rate,
      v_product.onlinerate,
      v_product.online_rate,
      v_product.retail_rate,
      v_product.restrate,
      v_product.selling_price,
      0
    )::numeric;

    IF v_unit_price <= 0 THEN
      RAISE EXCEPTION 'Product price missing for product %', v_product_id;
    END IF;

    v_line_total := v_unit_price * v_quantity;
    v_subtotal := v_subtotal + v_line_total;
  END LOOP;

  INSERT INTO public.orders (
    id,
    customer_id,
    customer_name,
    customer_phone,
    shipping_address,
    delivery_address,
    landmark,
    pincode,
    subtotal,
    total,
    total_amount,
    payment_method,
    payment_mode,
    payment_status,
    order_status,
    status,
    items,
    idempotency_key,
    created_at,
    updated_at
  )
  VALUES (
    gen_random_uuid()::text,
    p_customer_id,
    p_customer_name,
    p_customer_phone,
    p_shipping_address,
    p_shipping_address,
    p_landmark,
    p_pincode,
    v_subtotal,
    v_subtotal,
    v_subtotal,
    p_payment_method,
    p_payment_method,
    'pending',
    'pending',
    'pending',
    p_items,
    p_idempotency_key,
    NOW(),
    NOW()
  )
  RETURNING id INTO v_order_id;

  RETURN QUERY
  SELECT v_order_id,
         v_subtotal,
         v_subtotal,
         'pending',
         'pending';
END;
$$;

ALTER FUNCTION public.place_website_order_atomic(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb
) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.place_website_order_atomic(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.place_website_order_atomic(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb
) TO authenticated;

-- -----------------------------------------------------------------------------
-- 11. Wallet RPC: secure adjustment function
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.adjust_wallet_balance(
  p_user_id uuid,
  p_delta numeric,
  p_reason text,
  p_reference_type text DEFAULT NULL,
  p_reference_id text DEFAULT NULL
)
RETURNS TABLE (
  wallet_id bigint,
  new_balance numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_wallet_id bigint;
  v_current_balance numeric;
  v_new_balance numeric;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'user_id is required';
  END IF;

  INSERT INTO public.wallets (user_id, balance, currency, status)
  VALUES (p_user_id, 0, 'INR', 'active')
  ON CONFLICT (user_id)
  DO NOTHING;

  SELECT id, balance
    INTO v_wallet_id, v_current_balance
  FROM public.wallets
  WHERE user_id = p_user_id
  FOR UPDATE;

  v_new_balance := COALESCE(v_current_balance, 0) + COALESCE(p_delta, 0);

  UPDATE public.wallets
  SET balance = v_new_balance,
      updated_at = NOW()
  WHERE id = v_wallet_id;

  INSERT INTO public.wallet_transactions (
    wallet_id,
    user_id,
    entry_type,
    amount,
    currency,
    reference_type,
    reference_id,
    reason
  )
  VALUES (
    v_wallet_id,
    p_user_id,
    CASE WHEN COALESCE(p_delta, 0) >= 0 THEN 'credit' ELSE 'debit' END,
    ABS(COALESCE(p_delta, 0)),
    'INR',
    p_reference_type,
    p_reference_id,
    p_reason
  );

  RETURN QUERY
  SELECT v_wallet_id, v_new_balance;
END;
$$;

REVOKE ALL ON FUNCTION public.adjust_wallet_balance(uuid, numeric, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.adjust_wallet_balance(uuid, numeric, text, text, text) TO authenticated;

-- -----------------------------------------------------------------------------
-- 12. RLS activation and policies
-- -----------------------------------------------------------------------------
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_coupon_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "customers_read_own_addresses" ON public.customer_addresses;
CREATE POLICY "customers_read_own_addresses"
  ON public.customer_addresses FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_insert_own_addresses" ON public.customer_addresses;
CREATE POLICY "customers_insert_own_addresses"
  ON public.customer_addresses FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_update_own_addresses" ON public.customer_addresses;
CREATE POLICY "customers_update_own_addresses"
  ON public.customer_addresses FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_delete_own_addresses" ON public.customer_addresses;
CREATE POLICY "customers_delete_own_addresses"
  ON public.customer_addresses FOR DELETE TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_read_own_wallet" ON public.wallets;
CREATE POLICY "customers_read_own_wallet"
  ON public.wallets FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_read_own_wallet_transactions" ON public.wallet_transactions;
CREATE POLICY "customers_read_own_wallet_transactions"
  ON public.wallet_transactions FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_manage_own_notification_preferences" ON public.notification_preferences;
CREATE POLICY "customers_manage_own_notification_preferences"
  ON public.notification_preferences FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_manage_own_support_tickets" ON public.support_tickets;
CREATE POLICY "customers_manage_own_support_tickets"
  ON public.support_tickets FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "customers_see_own_coupon_usage" ON public.customer_coupon_usage;
CREATE POLICY "customers_see_own_coupon_usage"
  ON public.customer_coupon_usage FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "public_read_store_config" ON public.store_config;
CREATE POLICY "public_read_store_config"
  ON public.store_config FOR SELECT TO public
  USING (true);

-- -----------------------------------------------------------------------------
-- 13. Seed data (explicitly required only when environment is confirmed)
-- -----------------------------------------------------------------------------
INSERT INTO public.store_config (key, value, description)
VALUES (
  'serviceable_pincodes',
  '[]'::jsonb,
  'Delivery serviceability list. Must be filled by admin configuration.'
)
ON CONFLICT (key) DO NOTHING;

COMMIT;
