BEGIN;

CREATE TABLE IF NOT EXISTS public.customer_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  label TEXT NOT NULL DEFAULT 'Home',
  address TEXT NOT NULL,
  landmark TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user
  ON public.customer_addresses (user_id, created_at DESC);

ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their own addresses" ON public.customer_addresses;
CREATE POLICY "Users can read their own addresses"
  ON public.customer_addresses FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can add their own addresses" ON public.customer_addresses;
CREATE POLICY "Users can add their own addresses"
  ON public.customer_addresses FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can update their own addresses" ON public.customer_addresses;
CREATE POLICY "Users can update their own addresses"
  ON public.customer_addresses FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can delete their own addresses" ON public.customer_addresses;
CREATE POLICY "Users can delete their own addresses"
  ON public.customer_addresses FOR DELETE TO authenticated
  USING (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.customer_addresses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.customer_addresses_id_seq TO authenticated;

COMMIT;
