-- Public store assets controlled by the admin/catalog owner.
BEGIN;

CREATE TABLE IF NOT EXISTS public.store_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_key TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  alt_text TEXT NOT NULL DEFAULT 'NM Mart logo',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.store_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read active store assets" ON public.store_assets;
CREATE POLICY "Public can read active store assets"
  ON public.store_assets FOR SELECT
  TO anon, authenticated
  USING (is_active = TRUE);

DROP POLICY IF EXISTS "Admins can manage store assets" ON public.store_assets;
CREATE POLICY "Admins can manage store assets"
  ON public.store_assets FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.admin_users
      WHERE admin_users.auth_user_id = auth.uid()
        AND admin_users.is_active = TRUE
        AND COALESCE(lower(admin_users.status), 'active') = 'active'
        AND lower(admin_users.role) IN ('super_admin', 'cashier')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.admin_users
      WHERE admin_users.auth_user_id = auth.uid()
        AND admin_users.is_active = TRUE
        AND COALESCE(lower(admin_users.status), 'active') = 'active'
        AND lower(admin_users.role) IN ('super_admin', 'cashier')
    )
  );

GRANT SELECT ON public.store_assets TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.store_assets TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.store_assets_id_seq TO authenticated;

INSERT INTO public.store_assets (asset_key, image_url, alt_text)
VALUES ('main_logo', '/nm-mart-logo.png', 'NM Mart logo')
ON CONFLICT (asset_key) DO NOTHING;

COMMIT;
