BEGIN;

CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_items_user_updated_at
    ON public.cart_items (user_id, updated_at DESC);

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their cart" ON public.cart_items;
CREATE POLICY "Users can read their cart" ON public.cart_items
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can add to their cart" ON public.cart_items;
CREATE POLICY "Users can add to their cart" ON public.cart_items
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their cart" ON public.cart_items;
CREATE POLICY "Users can update their cart" ON public.cart_items
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can remove from their cart" ON public.cart_items;
CREATE POLICY "Users can remove from their cart" ON public.cart_items
    FOR DELETE USING (auth.uid() = user_id);

COMMIT;
