-- Customer wishlist storage. Product catalog remains authoritative in public.products.
BEGIN;

CREATE TABLE IF NOT EXISTS public.wishlist_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_barcode TEXT NOT NULL REFERENCES public.products(barcode) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT wishlist_items_user_product_key UNIQUE (user_id, product_barcode)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_items_user_id
  ON public.wishlist_items (user_id, created_at DESC);

ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their own wishlist" ON public.wishlist_items;
CREATE POLICY "Users can read their own wishlist"
  ON public.wishlist_items FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can add to their own wishlist" ON public.wishlist_items;
CREATE POLICY "Users can add to their own wishlist"
  ON public.wishlist_items FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can remove from their own wishlist" ON public.wishlist_items;
CREATE POLICY "Users can remove from their own wishlist"
  ON public.wishlist_items FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

GRANT SELECT, INSERT, DELETE ON public.wishlist_items TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.wishlist_items_id_seq TO authenticated;

COMMIT;
